In [35]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [54]:
df=pd.read_csv('iris.csv')

In [55]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

# euclidian distance


In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [11]:
result=[]
for i1,j1 in x.iterrows():
    for i2,j2 in x.iterrows():
        result.append(np.sqrt(np.sum((j2.values-j1.values)**2)))

In [12]:
result=np.array(result).reshape(150,150)
result=pd.DataFrame(result)
result

0         1         2         3         4         5         6    \
0    0.000000  0.538516  0.509902  0.648074  0.141421  0.616441  0.519615   
1    0.538516  0.000000  0.300000  0.331662  0.608276  1.090871  0.509902   
2    0.509902  0.300000  0.000000  0.244949  0.509902  1.086278  0.264575   
3    0.648074  0.331662  0.244949  0.000000  0.648074  1.166190  0.331662   
4    0.141421  0.608276  0.509902  0.648074  0.000000  0.616441  0.458258   
..        ...       ...       ...       ...       ...       ...       ...   
145  4.654031  4.700000  4.864155  4.745524  4.701064  4.284857  4.796874   
146  4.276681  4.249706  4.430576  4.288356  4.330127  3.988734  4.384062   
147  4.459821  4.498889  4.661545  4.533211  4.504442  4.102438  4.593474   
148  4.650806  4.718050  4.848711  4.719110  4.678675  4.264974  4.749737   
149  4.140048  4.153312  4.298837  4.149699  4.173727  3.818377  4.217819   

          7         8         9    ...       140       141       142  \
0    0.173205  0.921954  0.469042  ...  5.019960  4.636809  4.208325   
1    0.424264  0.509902  0.173205  ...  5.072475  4.702127  4.180909   
2    0.412311  0.435890  0.316228  ...  5.228767  4.868265  4.334743   
3    0.500000  0.300000  0.316228  ...  5.104900  4.760252  4.177320   
4    0.223607  0.921954  0.529150  ...  5.061620  4.686150  4.246175   
..        ...       ...       ...  ...       ...       ...       ...   
145  4.598913  4.914265  4.666905  ...  0.424264  0.244949  1.034408   
146  4.200000  4.429447  4.220190  ...  1.063015  0.943398  0.547723   
147  4.397727  4.701064  4.457578  ...  0.608276  0.519615  0.774597   
148  4.589118  4.888763  4.672259  ...  0.624500  0.818535  0.948683   
149  4.060788  4.302325  4.106093  ...  1.122497  1.122497  0.331662   

          143       144       145       146       147       148       149  
0    5.257376  5.136146  4.654031  4.276681  4.459821  4.650806  4.140048  
1    5.320714  5.206726  4.700000  4.249706  4.498889  4.718050  4.153312  
2    5.475400  5.353504  4.864155  4.430576  4.661545  4.848711  4.298837  
3    5.349766  5.232590  4.745524  4.288356  4.533211  4.719110  4.149699  
4    5.297169  5.173007  4.701064  4.330127  4.504442  4.678675  4.173727  
..        ...       ...       ...       ...       ...       ...       ...  
145  0.734847  0.616441  0.000000  0.781025  0.360555  0.670820  0.948683  
146  1.307670  1.284523  0.781025  0.000000  0.583095  1.067708  0.655744  
147  0.842615  0.793725  0.360555  0.583095  0.000000  0.616441  0.640312  
148  0.806226  0.624500  0.670820  1.067708  0.616441  0.000000  0.768115  
149  1.319091  1.256981  0.948683  0.655744  0.640312  0.768115  0.000000  

[150 rows x 150 columns]

# simple method to find distance

In [15]:
from sklearn.metrics import pairwise_distances
pd.DataFrame(pairwise_distances(x.values))


0         1         2         3         4         5         6    \
0    0.000000  0.538516  0.509902  0.648074  0.141421  0.616441  0.519615   
1    0.538516  0.000000  0.300000  0.331662  0.608276  1.090871  0.509902   
2    0.509902  0.300000  0.000000  0.244949  0.509902  1.086278  0.264575   
3    0.648074  0.331662  0.244949  0.000000  0.648074  1.166190  0.331662   
4    0.141421  0.608276  0.509902  0.648074  0.000000  0.616441  0.458258   
..        ...       ...       ...       ...       ...       ...       ...   
145  4.654031  4.700000  4.864155  4.745524  4.701064  4.284857  4.796874   
146  4.276681  4.249706  4.430576  4.288356  4.330127  3.988734  4.384062   
147  4.459821  4.498889  4.661545  4.533211  4.504442  4.102438  4.593474   
148  4.650806  4.718050  4.848711  4.719110  4.678675  4.264974  4.749737   
149  4.140048  4.153312  4.298837  4.149699  4.173727  3.818377  4.217819   

          7         8         9    ...       140       141       142  \
0    0.173205  0.921954  0.469042  ...  5.019960  4.636809  4.208325   
1    0.424264  0.509902  0.173205  ...  5.072475  4.702127  4.180909   
2    0.412311  0.435890  0.316228  ...  5.228767  4.868265  4.334743   
3    0.500000  0.300000  0.316228  ...  5.104900  4.760252  4.177320   
4    0.223607  0.921954  0.529150  ...  5.061620  4.686150  4.246175   
..        ...       ...       ...  ...       ...       ...       ...   
145  4.598913  4.914265  4.666905  ...  0.424264  0.244949  1.034408   
146  4.200000  4.429447  4.220190  ...  1.063015  0.943398  0.547723   
147  4.397727  4.701064  4.457578  ...  0.608276  0.519615  0.774597   
148  4.589118  4.888763  4.672259  ...  0.624500  0.818535  0.948683   
149  4.060788  4.302325  4.106093  ...  1.122497  1.122497  0.331662   

          143       144       145       146       147       148       149  
0    5.257376  5.136146  4.654031  4.276681  4.459821  4.650806  4.140048  
1    5.320714  5.206726  4.700000  4.249706  4.498889  4.718050  4.153312  
2    5.475400  5.353504  4.864155  4.430576  4.661545  4.848711  4.298837  
3    5.349766  5.232590  4.745524  4.288356  4.533211  4.719110  4.149699  
4    5.297169  5.173007  4.701064  4.330127  4.504442  4.678675  4.173727  
..        ...       ...       ...       ...       ...       ...       ...  
145  0.734847  0.616441  0.000000  0.781025  0.360555  0.670820  0.948683  
146  1.307670  1.284523  0.781025  0.000000  0.583095  1.067708  0.655744  
147  0.842615  0.793725  0.360555  0.583095  0.000000  0.616441  0.640312  
148  0.806226  0.624500  0.670820  1.067708  0.616441  0.000000  0.768115  
149  1.319091  1.256981  0.948683  0.655744  0.640312  0.768115  0.000000  

[150 rows x 150 columns]

# splitting train and test

In [56]:

x_train,x_test = train_test_split(df1_sc, test_size=0.3, random_state=13)

# scaling

In [57]:
df1=df.drop(['variety'], axis = 1)

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
sc= StandardScaler()
df1_sc= sc.fit_transform(x_train)

In [60]:
df1_sc

array([[ 1.64140580e+00,  1.35045695e+00,  1.37610194e+00,
         1.77370775e+00],
       [-8.19029134e-01,  8.67329248e-01, -1.23551785e+00,
        -1.26855377e+00],
       [-9.36192702e-01, -1.78987309e+00, -2.13579673e-01,
        -2.10375848e-01],
       [-1.63917411e+00,  3.84201550e-01, -1.34906654e+00,
        -1.26855377e+00],
       [ 8.21260821e-01, -5.82053846e-01,  5.24486791e-01,
         4.50985350e-01],
       [-1.16047725e-01,  1.83358464e+00, -1.12196917e+00,
        -1.13628153e+00],
       [-1.16047725e-01, -9.89261477e-02,  2.97389418e-01,
         5.41686315e-02],
       [ 1.18279412e-01,  3.84201550e-01,  6.38035478e-01,
         8.47802069e-01],
       [ 1.17275153e+00,  3.84201550e-01,  1.26255325e+00,
         1.50916327e+00],
       [-1.05335627e+00,  1.42637701e-01, -1.23551785e+00,
        -1.40082600e+00],
       [-3.50374861e-01, -1.54830924e+00,  7.02920442e-02,
        -7.81036082e-02],
       [-1.28768341e+00,  3.84201550e-01, -1.17874351e+00,
      

# step-2 covariance

# PCA

In [61]:
pca = PCA(n_components=4)       

In [62]:
pca1=pca.fit_transform(x_train)

In [63]:
pca1

array([[ 2.53970253e+00, -1.70789639e+00,  4.10963466e-01,
         1.23691540e-01],
       [-2.04547073e+00, -5.59775133e-01, -1.63893643e-01,
        -2.15540925e-03],
       [-5.03669911e-01,  1.91551350e+00,  1.15179838e-01,
         5.75543366e-03],
       [-2.50953318e+00,  1.40953356e-01,  3.16053283e-01,
        -8.91136863e-02],
       [ 1.12568097e+00,  2.75813806e-01, -3.86374853e-01,
         1.16698288e-01],
       [-1.65009672e+00, -1.65862655e+00, -3.60559561e-01,
         6.23798329e-02],
       [ 1.53182961e-01,  1.38258545e-01,  1.36283406e-01,
        -2.31688970e-01],
       [ 8.58898798e-01, -3.62908492e-01,  6.26245335e-01,
        -8.50813831e-02],
       [ 2.20506938e+00, -6.85665988e-01,  3.49768510e-01,
         5.80698527e-02],
       [-2.14176927e+00,  1.71621982e-01, -2.43145856e-01,
        -5.18800728e-02],
       [ 3.71738988e-02,  1.51586871e+00, -1.40754740e-01,
        -1.40117591e-02],
       [-2.20702398e+00,  3.21418543e-02,  7.81759616e-02,
      

In [64]:
pca.fit_transform(x_train).shape

(105, 4)

In [65]:
df2=pd.DataFrame(pca1)

In [66]:
df2

0         1         2         3
0    2.539703 -1.707896  0.410963  0.123692
1   -2.045471 -0.559775 -0.163894 -0.002155
2   -0.503670  1.915513  0.115180  0.005755
3   -2.509533  0.140953  0.316053 -0.089114
4    1.125681  0.275814 -0.386375  0.116698
..        ...       ...       ...       ...
100  1.212716  0.394775  0.141927  0.129742
101 -0.536946  1.434398  0.202860  0.186801
102 -1.949196 -1.770198  0.010442  0.183166
103  0.771719  0.089914 -0.434770  0.054532
104  0.234309  0.748201 -0.140795  0.023825

[105 rows x 4 columns]

In [67]:
df2.corr()

0             1             2             3
0  1.000000e+00  2.887375e-16  1.434460e-16 -5.623655e-17
1  2.887375e-16  1.000000e+00  2.562954e-16 -4.346228e-17
2  1.434460e-16  2.562954e-16  1.000000e+00 -1.209842e-16
3 -5.623655e-17 -4.346228e-17 -1.209842e-16  1.000000e+00

In [68]:
df2.var()

0    2.917139
1    0.922714
2    0.153568
3    0.014947
dtype: float64

In [51]:
pca.explained_variance_ratio_

array([0.72776229, 0.23019691, 0.03831193, 0.00372887])

# inverse transform

In [69]:
pca2=pca.inverse_transform(pca1)

In [70]:
pca2

array([[ 1.64384411e+00,  1.24920112e+00,  1.33113254e+00,
         1.71209594e+00],
       [-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00, -1.74335684e+00, -2.60315415e-01,
        -2.62386821e-01],
       [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [ 7.95669016e-01, -5.92373012e-01,  4.78571135e-01,
         3.95774101e-01],
       [-1.73673948e-01,  1.70959465e+00, -1.16971425e+00,
        -1.18381211e+00],
       [-1.73673948e-01, -1.31979479e-01,  2.51221427e-01,
         8.77547895e-04],
       [ 6.86617933e-02,  3.28414053e-01,  5.92245988e-01,
         7.90670654e-01],
       [ 1.15917263e+00,  3.28414053e-01,  1.21745768e+00,
         1.44883158e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-4.16009689e-01, -1.51316008e+00,  2.38717193e-02,
        -1.30754636e-01],
       [-1.38535265e+00,  3.28414053e-01, -1.22655167e+00,
      