In [43]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [5]:
df=pd.read_csv('iris.csv')

In [6]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

# splitting x and y

In [14]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

# labelencoding

In [21]:
le=LabelEncoder()
y_encoded =le.fit_transform(df.variety)

In [22]:
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

# splitting train and test

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=13)

# scandardscaler

In [36]:
ss= StandardScaler()
x_train_ss= ss.fit_transform(x_train)

In [37]:
x_train_ss

array([[ 1.64140580e+00,  1.35045695e+00,  1.37610194e+00,
         1.77370775e+00],
       [-8.19029134e-01,  8.67329248e-01, -1.23551785e+00,
        -1.26855377e+00],
       [-9.36192702e-01, -1.78987309e+00, -2.13579673e-01,
        -2.10375848e-01],
       [-1.63917411e+00,  3.84201550e-01, -1.34906654e+00,
        -1.26855377e+00],
       [ 8.21260821e-01, -5.82053846e-01,  5.24486791e-01,
         4.50985350e-01],
       [-1.16047725e-01,  1.83358464e+00, -1.12196917e+00,
        -1.13628153e+00],
       [-1.16047725e-01, -9.89261477e-02,  2.97389418e-01,
         5.41686315e-02],
       [ 1.18279412e-01,  3.84201550e-01,  6.38035478e-01,
         8.47802069e-01],
       [ 1.17275153e+00,  3.84201550e-01,  1.26255325e+00,
         1.50916327e+00],
       [-1.05335627e+00,  1.42637701e-01, -1.23551785e+00,
        -1.40082600e+00],
       [-3.50374861e-01, -1.54830924e+00,  7.02920442e-02,
        -7.81036082e-02],
       [-1.28768341e+00,  3.84201550e-01, -1.17874351e+00,
      

In [38]:
x_test_ss=ss.transform(x_test)

In [39]:
pca=PCA(0.95)

In [40]:
pca_x_train=pca.fit_transform(x_train_ss)

In [41]:
pca_x_test= pca.transform(x_test_ss)

In [45]:
model=LogisticRegression()
model.fit(pca_x_train, y_train)

LogisticRegression()

# testing

In [46]:
pca_x_test

array([[ 0.42851044,  0.58876694],
       [ 0.01934082,  0.39030631],
       [-2.04094623, -1.24274042],
       [ 1.19216298,  0.76326876],
       [ 1.97297438, -0.29446197],
       [-2.19897621, -2.52906367],
       [ 2.89273582, -0.6261317 ],
       [ 1.36467606,  0.58359073],
       [-2.20413597, -1.46422867],
       [ 0.28321267,  1.12367223],
       [ 1.0069962 ,  0.00386452],
       [ 1.1591333 ,  0.3663967 ],
       [ 0.9984765 ,  1.51693843],
       [-1.95215515, -1.46980637],
       [ 1.52617404,  0.51533391],
       [-2.07807314,  0.25139244],
       [ 1.10349735, -0.0319665 ],
       [ 1.96000865, -0.18704813],
       [ 0.6999006 , -0.01900466],
       [-2.30711029,  0.85486984],
       [ 0.72423618,  0.24260881],
       [-1.97787047, -3.06766102],
       [-2.06015161, -0.78070146],
       [ 2.49042292, -0.04311492],
       [ 0.30093025,  0.23173326],
       [ 2.14498366, -0.96001635],
       [-1.98669001, -2.1806184 ],
       [ 3.3404906 ,  0.29658351],
       [ 0.77838433,

In [47]:
pred=model.predict(pca_x_test)

In [48]:
pred

array(['Versicolor', 'Versicolor', 'Setosa', 'Virginica', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Setosa', 'Virginica',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Versicolor', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Setosa', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Virginica',
       'Versicolor', 'Setosa', 'Versicolor', 'Virginica', 'Setosa',
       'Setosa', 'Virginica', 'Versicolor', 'Virginica', 'Virginica'],
      dtype=object)

In [49]:
model.score(pca_x_test,y_test)

0.9111111111111111